### ISSUE TITLE
openwrt

### ISSUE THREAD

**Issue by dtaht** [SentryPeer/SentryPeer#5]
Just wanted to give you a thumbs up. 

An openwrt package would be nice. Also despite sqlite being nice there are other database engines that might be more efficient, like good ole berkeley db.

**Comment by ghenry** [comment]
Hi Dave,

Apologies I missed this! Just spotted it.

Thanks, I appreciate the encouragement :)

I was planning lmdb too, but thought a plain sqlite db could be accessed by anyone to get started with.

I'll add it as an option when I get to it.

Don't forget to like and subscribe :)

**Comment by ghenry** [comment]
If you've got any experience packaging for it or can point me to their docs, that would be great.

Or even a PR with docs and an example to go in the packaging folder. That's asking too much though :)

**Comment by ghenry** [comment]
@dtaht How did you find out about SentryPeer?

**Comment by ghenry** [comment]
Hi @dtaht Im going to close this now. Let me know if you can help test this on openwrt.

Thanks for trying SentryPeer!

**Comment by dtaht** [comment]
I think you posted on nanog. I will keep paying attention here.

**Comment by ghenry** [comment]
Thanks @dtaht
