### ISSUE TITLE
Enhancement: support for Arch Linux

### ISSUE THREAD

**Issue by D3vil0p3r** [SentryPeer/SentryPeer#81]
**Is your feature request related to a problem? Please describe.**
It could be very nice if SentryPeer could support Arch Linux in order to be used on distros as BlackArch or Athena OS. Is it possible to build it from source? Which are the right dependencies to install on Arch Linux for building SentryPeer?

Currently I built it by using the following dependencies:
```
'autoconf' 'autoconf-archive' 'automake' 'cmocka' 'curl' 'git' 'jansson' 'libmicrohttpd' 'libosip2 (AUR)' 'opendht' 'pcre2' 'sqlite' 'uuid'
```
The main problem is the usage of OpenDHT because I see that SentyPeer uses `opendht/opendht_c.h` header file, while `opendht` Arch Linux package provides `opendht.h` Do they contain the same code? On [OpenGHT project](https://github.com/savoirfairelinux/opendht) I cannot find the file `opendht_c.h` on the source files.

Furthermore, `configure.ac` checks for `opendht-c` package, while on Arch Linux the package name is `opendht` (see: https://github.com/SentryPeer/SentryPeer/blob/9c0f03d0c4b6b1e03c94a56b7ae43f2a5b0e3c27/configure.ac#L101).

If I try to build with all these changes for enabling OpenDHT, I get the error:
```
gcc -DHAVE_CONFIG_H -I.    -Wall -Werror -Wextra -Wpedantic -pedantic -Wformat=2 -Wno-unused-parameter -Wshadow -Wwrite-strings -Wstrict-prototypes -Wold-style-definition -Wnested-externs -Wmissing-include-dirs -Wredundant-decls -std=c18 -D_FORTIFY_SOURCE=2 -fpie -fpic -g3 -O2 -fstack-protector-strong -grecord-gcc-switches -Werror=format-security -Werror=implicit-function-declaration -Wmisleading-indentation  -g -O2 -pthread -I/usr/include/p11-kit-1  -MT src/regex_match.o -MD -MP -MF $depbase.Tpo -c -o src/regex_match.o src/regex_match.c &&\
mv -f $depbase.Tpo $depbase.Po
In file included from /usr/include/opendht/infohash.h:22,
                 from /usr/include/opendht/dhtrunner.h:24,
                 from /usr/include/opendht.h:21,
                 from src/conf.h:28,
                 from src/http_daemon.c:14:
/usr/include/opendht/rng.h:21:10: fatal error: random: No such file or directory
   21 | #include <random>
      |          ^~~~~~~~
compilation terminated.
make[1]: *** [Makefile:1097: src/http_daemon.o] Error 1
make[1]: *** Waiting for unfinished jobs....
In file included from /usr/include/opendht/infohash.h:22,
                 from /usr/include/opendht/dhtrunner.h:24,
                 from /usr/include/opendht.h:21,
                 from src/conf.h:28,
                 from src/regex_match.c:22:
```
and I'm not sure if `#include <random>` works by `gcc` or only by `g++` with `-std=c++11` param. Where I can switch from `gcc` to `g++`?

**Comment by ghenry** [comment]
I'm pretty sure it can be. Would you like to build from source or it to be
packaged properly?

I can download Arch Linux and tun on virtualbox and test for you.

**Comment by D3vil0p3r** [comment]
> I'm pretty sure it can be. Would you like to build from source or it to be packaged properly? I can download Arch Linux and tun on virtualbox and test for you.

I would like to build from source. In this manner, I can prepare a PKGBUILD and publish it on BlackArch repository.

**Comment by ghenry** [comment]
Excellent, thanks!

Can we put the PKGBUILD into an Arch Linux folder here?

https://github.com/SentryPeer/SentryPeer/tree/main/packaging

**Comment by ghenry** [comment]
Hi @D3vil0p3r 

Do you need to run with p2p mode?

KaliLinux and T-Pot don't. You could disable it. When I did the packaging of it for Alpine Linux, you need certain things on to get the C libs built of OpenDHT:

https://git.alpinelinux.org/aports/tree/testing/opendht/APKBUILD

Thanks.

**Comment by ghenry** [comment]
See this https://git.alpinelinux.org/aports/tree/testing/opendht/APKBUILD#n44

**Comment by ghenry** [comment]
I reckon the Arch Linux version of OpenDHT is either old or doesn't have C libs enabled. I pushed all the C libs of OpenDHT in that project too.

**Comment by D3vil0p3r** [comment]
Hey @ghenry . I would like to run with p2p mode to have all features of the tool.

On which project did you push all the C libs of OpenDHT?

**Comment by ghenry** [comment]
Cool!

The C libs are only built on OpenDHT if you enable with the cmake options like so - https://git.alpinelinux.org/aports/tree/testing/opendht/APKBUILD#n44

If the bundled version of OpenDHT in Arch doesn't build with them on, opendht_c.h won't be there:

`-DOPENDHT_C=ON`

Thanks.

**Comment by D3vil0p3r** [comment]
Ok, let me to do a test. I will try to create a new package called `opendht-c` where I enable those arguments.

**Comment by ghenry** [comment]
Check this is on too, as it's handy:

-DOPENDHT_TOOLS=ON

The c libs should generate a libopendht-c.so

like https://git.alpinelinux.org/aports/tree/testing/opendht/APKBUILD#n63

**Comment by D3vil0p3r** [comment]
@ghenry It works!
```
SentryPeer node id: 7bc7205f-f195-482e-8d4f-6d9b842f7251
Starting sentrypeer...
API mode enabled, starting http daemon...
SIP mode enabled...
Peer to Peer DHT mode enabled...
Starting peer to peer DHT mode using OpenDHT-C lib version '2.5.4'...
Peer to peer DHT mode started.
DHT InfoHash for key 'bad_actors' is: 14d30143330e2e0e922ed4028a60ff96a59800ad
Bootstrapping the DHT
Waiting 5 seconds for bootstrapping to bootstrap.sentrypeer.org...
Configuring local address...
Creating sockets...
Binding sockets to local address...
Listening for incoming UDP connections...
SIP responsive mode enabled. Will reply to SIP probes...
Listening for incoming TCP connections...
```

I would like to ask you one suggestion:

I created `opendht-c` package with the following PKGBUILD:
```pkgbuild
pkgname=opendht-c
pkgver=v2.5.4.r0.g27978f3b
pkgrel=1
epoch=1
pkgdesc="C++17 Distributed Hash Table implementation."
arch=('any')
url='https://github.com/savoirfairelinux/opendht'
license=('GPL3')
depends=('argon2' 'asio' 'gnutls' 'jsoncpp' 'nettle' 'readline')
makedepends=('cmake' 'cython' 'fmt' 'git' 'http-parser' 'msgpack-cxx' 'python' 'python-setuptools' 'restinio' 'samurai')
checkdepends=('cppunit-dev')
provides=('opendht')
conflicts=('opendht')
source=("git+https://github.com/savoirfairelinux/${pkgname%-c}.git")
sha512sums=('SKIP')

pkgver() {
  cd "${pkgname%-c}"

  git describe --long --tags | sed 's/\([^-]*-g\)/r\1/;s/-/./g'
}

prepare() {
  cd "${srcdir}/${pkgname%-*}"

  install -d build
}

build() {
  cd "${srcdir}/${pkgname%-c}/build"

  cmake .. \
    -DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_SHARED_LIBS=True \
		-DCMAKE_BUILD_TYPE=MinSizeRel \
		-DOPENDHT_C=ON \
		-DOPENDHT_TOOLS=ON \
		-DOPENDHT_PYTHON=ON \
		-DOPENDHT_HTTP=ON \
		-DOPENDHT_PUSH_NOTIFICATIONS=ON \
		-DBUILD_TESTING="$(want_check && echo ON || echo OFF)" \
		$CMAKE_CROSSOPTS .
  make
}

package() {
  cd "${srcdir}/${pkgname%-c}/build"

  make DESTDIR="${pkgdir}" install
  install -D -m644 ../README.md "${pkgdir}/usr/share/doc/opendht/README.md"
}
```
I started the code from [opendht-git](https://aur.archlinux.org/packages/opendht-git) AUR package and I used the cmake arguments you suggested me from Alpine. My doubt is related to the dependencies. On AUR package, I have in depends() the following:
```
depends=('argon2' 'asio' 'gnutls' 'jsoncpp' 'nettle' 'readline')
```
In Alpine those dependencies are moved to `makedepends()`. So, what I should do? Should I move them to `makedepends()` or leaving them in `depends()`?

**Comment by ghenry** [comment]
Move them to makedepends then try to run it and see if it fails looking for libs. Then you'll know it "depends" on them at runtime :-)

**Comment by D3vil0p3r** [comment]
@ghenry I submitted the package (and the missing dependencies) to BlackArch repository: https://github.com/BlackArch/blackarch/pull/3816

When the Pull Request will be merged (usually in few days), SentryPeer can be installed by BlackArch repository on all Arch-based distros by `sudo pacman -S sentrypeer`.

**Comment by ghenry** [comment]
Awesome work @D3vil0p3r 

Well done!

Any reason you went for 5.3.0 and not 5.3.1?

What are you planning to use SentryPeer for?

I'm busy getting sentrypeer.com ready. See this for some description:

**Comment by ghenry** [comment]
https://community.freepbx.org/t/custom-module-development-starter-module-to-read-and-publishing-process/88563/6?u=ghenry 
https://community.freepbx.org/t/custom-module-development-starter-module-to-read-and-publishing-process/88563/18?u=ghenry

**Comment by D3vil0p3r** [comment]
> Any reason you went for 5.3.0 and not 5.3.1?

Ops. I missed it. I updated the version. Thanks for the tip.

> What are you planning to use SentryPeer for?

Currently I would like to bring this tool also to BlackArch and Athena OS users for defensive purposes. Currently I don't still have a particular purpose, but I will test it as soon as I end my activities!

**Comment by ghenry** [comment]
Cool. Thanks for doing this!

Excellent. Let me know if you have any questions.

**Comment by ghenry** [comment]
Oh, two last questions before you go :-)

1. Where did you find out about SentryPeer? 
2. Got any feature requests or feedback?

Thanks!

**Comment by D3vil0p3r** [comment]
> 

I found it while I explored the new Kali Linux Purple! Still I didn't receive any feedback or request about that.

**Comment by ghenry** [comment]
Ah, cool. Thanks again. I'll close this now.

Please keep an eye out for sentrypeer.com and maybe follow
https://twitter.com/SentryPeer and give the project a star :-)

https://github.com/SentryPeer/SentryPeer
